### ISSUE TITLE
Bug connexion

### ISSUE THREAD

**Issue by Fizo55** [Syleze/EastMile-s-ReBirth#13]
Hello, when I try to access the server I use this error message:
[WORLD] MySql.Data.MySqlClient.MySqlException (0x80004005): Field 'game_server' does not have a default value
   To MySql.Data.MySqlClient.MySqlStream.ReadPacket ()
   To MySql.Data.MySqlClient.NativeDriver.GetResult (Int32 & affectedRow, Int64 & insertedId)
   To MySql.Data.MySqlClient.Driver.GetResult (Int32 statementId, Int32 & affectedRows, Int64 & insertedId)
   To MySql.Data.MySqlClient.Driver.NextResult (Int32 statementId, Boolean force)
   To MySql.Data.MySqlClient.MySqlDataReader.NextResult ()
   To MySql.Data.MySqlClient.MySqlCommand.ExecuteReader (CommandBehavior behavior)
   To MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery ()
   To EastMile_s_ReBirth.Objects.Player.Player.CharNEW (String [] packetSplit) in C: \ Users \ Elias \ Documents \ Visual Studio 2015 \ Projects \ EastMile's ReBirth \ EastMile ReBirth \ Objects \ Player \ Player.cs:
   To EastMile_s_ReBirth.Network.World.PacketHandler.Answer (C: \ Users \ Elias \ Documents \ Visual Studio 2015 \ Projects \ EastMile \ ReBirth \ EastMile \ ReBirth \ Network \ World \ PacketHandler.cs: 34
   To EastMile_s_ReBirth.Network.World.Client.Socket_OnDataReceived (Byte [] packet) in C: \ Users \ Elias \ Documents \ Visual Studio 2015 \ Projects \ EastMile's ReBirth \
TARGET = MySql.Data.MySqlClient.MySqlPacket ReadPacket ()
 MESSAGE = Field 'game_server' does not have a default value

**Comment by Syleze** [comment]
Hello, did you change the code ?

**Comment by Fizo55** [comment]
No, I just log in with the username admin and the test password and when we finish creating his character there is the error message I dis not change the code and the portal when we Enter the Aréna aften we can no longer come out

**Comment by Syleze** [comment]
Your problem is weird because there is no field called "game_server". Not in the code and not in the database. So why do you have a reference to it ? Do you use the correct database ? Try to update it with the one I put in the solution.

**Comment by Syleze** [comment]
You can delete 'game_server' field in em_characters table, there is currently no use of it.
